version: "3.8"
services:
  # db:
  #   image: postgres:15.2-alpine
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_DB: chat-dbdocker
  #   volumes:
  #     - ./data:/var/lib/postgresql/data
  #   restart: always
  #   ports:
  #     - "5433:5432"
  # redis-store:
  #   image: redis:6.2-alpine
  #   restart: always
  #   ports:
  #     - '6379:6379'
  #   volumes:
  #     - ./data:/var/lib/cache/data
  #   environment:
